### PR TITLE
Add test for each class

### PR DESCRIPTION
**Pull request by Ney2**
This is a PR for adding test to the classes using Rspec
1. Install Rspec
2. Add test for each class

### CODE REVIEW

**Comment by Ney2** [comment]
Dear Reviewer,
Thank you for reviewing my project. I was assigned two coding partners this week but unfortunately, both of them aren't available for this week so I did the project solo. I hope you consider this situation and review my project.
Thank you,
Kidist.

**Review by roshan-bajgain — COMMENTED** [review]
Hi @Ney2, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you did alone but this is pair programming and what I can suggest to you is that please contact student success at Microverse so that they can help you immediately. If you did so then please attach the screenshot so another reviewer can continue the review process

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ney2** [comment]
Okay thank you for your comment

**Comment by AngomRanjan** [comment]
## Fulfilled the requirements as suggested by the previous reviewer

**Review by Reem-lab — APPROVED** [review]
# Hi Team,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the Unit tests✅
📌 Good commit messages ✅
📌 Professional README ✅


## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
